const $ = (id) => document.getElementById(id);
const words = {
 ko: {heading:'문장을 넘어, 선택으로.',subtitle:'상황과 선택지를 입력하고, 모델의 판단을 확인하세요.',examples:'예제로 시작하기',examplesNote:'검증된 영어 예제입니다. 내용을 바꿔 직접 비교해 보세요.',input:'입력',state:'상황',stateNote:'모델이 판단에 사용할 정보 · 최대 1,024토큰',question:'질문',options:'선택지',add:'선택지 추가',submit:'선택 결과 확인',running:'모델이 판단하고 있습니다…',result:'모델의 선택',emptyTitle:'어떤 선택을 할까요?',emptyText:'입력을 확인하고 실행하면\n선택지별 확률이 여기에 표시됩니다.',probabilityNote:'확률은 주어진 선택지 간 상대적인 모델 확률입니다. 정답을 보장하지 않습니다.',actual:'실제 로컬 모델 응답',json:'JSON 보기',copy:'JSON 복사',copied:'복사했습니다',copyFail:'복사하지 못했습니다. JSON을 직접 선택해 복사해 주세요.',footer:'로컬 실행 · 텍스트 선택 모델 · 최대 2,048토큰',api:'API 문서',ready:'모델 연결됨',checking:'연결 확인 중',starting:'모델 준비 중',offline:'모델 연결 안 됨',failed:'모델 시작 실패',wrong_model:'다른 모델이 연결됨',offlineNotice:'모델 서버에 연결할 수 없습니다. run_windows.bat로 모델을 시작하거나, run_playground.bat로 함께 실행하세요.',startingNotice:'모델을 준비하고 있습니다. 첫 실행은 커널 컴파일로 몇 분 걸릴 수 있습니다. 준비되면 실행 버튼이 활성화됩니다.',failedNotice:'모델 시작에 실패했습니다. artifacts 폴더의 playground-model.log를 확인하세요.',wrong_modelNotice:'연결된 서버에 kev-4b-experimental 모델이 없습니다. Kev 모델 서버를 실행하세요.',remove:'선택지 삭제',option:'선택지',invalid:'상황과 질문, 서로 다른 선택지 2~12개를 입력해 주세요.',request:'전체 요청',tokens:'토큰',genericError:'요청을 처리하지 못했습니다. 연결 상태와 입력 길이를 확인해 주세요.',longInput:'입력이 너무 깁니다. 상황은 1,024토큰, 전체 입력은 2,048토큰 이내로 줄여 주세요.',busy:'다른 요청을 처리 중입니다. 잠시 후 다시 시도해 주세요.'},
 en: {heading:'Beyond words. Make a choice.',subtitle:'Give the model context and options. See how it decides.',examples:'Start with an example',examplesNote:'Tested English examples. Edit the inputs and compare the results.',input:'Input',state:'State',stateNote:'Information for the decision · up to 1,024 tokens',question:'Question',options:'Options',add:'Add option',submit:'Run decision',running:'The model is deciding…',result:'The model’s choice',emptyTitle:'What will it choose?',emptyText:'Review the input and run a decision.\nOption probabilities will appear here.',probabilityNote:'These are relative model probabilities among the supplied options, not a guarantee of correctness.',actual:'Actual local model response',json:'View JSON',copy:'Copy JSON',copied:'Copied',copyFail:'Could not copy. Select and copy the JSON manually.',footer:'Runs locally · text decisions · up to 2,048 tokens',api:'API docs',ready:'Model connected',checking:'Checking connection',starting:'Preparing model',offline:'Model offline',failed:'Model startup failed',wrong_model:'Different model connected',offlineNotice:'Cannot reach the model. Start run_windows.bat, or use run_playground.bat to launch both services.',startingNotice:'The model is starting. First startup may take several minutes to compile kernels. Run will become available when ready.',failedNotice:'Model startup failed. Check playground-model.log under artifacts.',wrong_modelNotice:'The connected server does not have kev-4b-experimental. Start the Kev model server.',remove:'Remove option',option:'Option',invalid:'Enter a state, a question, and 2–12 distinct, nonempty options.',request:'Total request',tokens:'tokens',genericError:'Request failed. Check the model connection and input length.',longInput:'Input is too long. Keep the state within 1,024 tokens and the full row within 2,048 tokens.',busy:'Another request is running. Please retry shortly.'}
};
let lang = 'ko', examples = [], currentExample = '', output = null, busy = false, health = {ready:false,status:'checking'};
const t = (key) => words[lang][key] || key;
const arrow = '<svg width="15" height="15" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m9 5 7 7-7 7" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const trash = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>';
function clearResult() { output=null; $('result').hidden=true; $('response-section').hidden=true; $('empty-result').hidden=false; $('error').hidden=true; }
function renderExamples() {
 $('examples').replaceChildren();
 examples.forEach((example,i)=>{const b=document.createElement('button'); b.type='button'; b.className='example'; b.disabled=busy; b.setAttribute('aria-current',String(currentExample===example.id)); b.title=example['description_'+lang]; const n=document.createElement('span');n.className='example-number';n.textContent=i+1;const label=document.createElement('span');label.textContent=example['title_'+lang];b.append(n,label);b.insertAdjacentHTML('beforeend',arrow);b.onclick=()=>loadExample(example);$('examples').append(b);});
}
function optionValues(){return [...$('options').querySelectorAll('input')].map(el=>el.value);}
function addOption(value='') {
 const row=document.createElement('div');row.className='option-row';const letter=document.createElement('span');letter.className='option-letter';letter.setAttribute('aria-hidden','true');const input=document.createElement('input');input.value=value;input.required=true;input.maxLength=1000;const remove=document.createElement('button');remove.type='button';remove.className='remove';remove.innerHTML=trash;remove.onclick=()=>{row.remove();renumber();clearResult();};row.append(letter,input,remove);$('options').append(row);renumber();return input;
}
function renumber(){const rows=[...$('options').children];rows.forEach((row,i)=>{row.querySelector('.option-letter').textContent=String.fromCharCode(65+i);row.querySelector('input').setAttribute('aria-label',`${t('option')} ${i+1}`);const button=row.querySelector('button');button.disabled=rows.length<=2;button.setAttribute('aria-label',`${t('remove')} ${i+1}`);});$('add-option').disabled=rows.length>=12;}
function loadExample(example){currentExample=example.id;$('state').value=example.state;$('question').value=example.question;$('options').replaceChildren();example.options.forEach(addOption);clearResult();renderExamples();}
function showHealth(){ $('connection').classList.toggle('ready',health.ready);$('connection-text').textContent=t(health.status);const notice=$('server-notice');notice.hidden=health.ready||health.status==='checking';notice.textContent=t(health.status+'Notice');$('submit').disabled=busy||!health.ready;$('submit-text').textContent=t(busy?'running':'submit'); }
async function refreshHealth(){try{const r=await fetch('/api/health');if(!r.ok)throw Error();health=await r.json();}catch{health={ready:false,status:'offline'};}showHealth();}
function renderResult(){if(!output)return;$('probabilities').replaceChildren();output.probabilities.forEach((entry,i)=>{const row=document.createElement('div');row.className='prob-row'+(i===output.selected_index?' selected':'');const label=document.createElement('div');label.className='prob-label';const letter=document.createElement('span');letter.className='option-letter';letter.textContent=String.fromCharCode(65+i);const text=document.createElement('span');text.className='option-text';text.textContent=entry.option;const percent=document.createElement('strong');percent.textContent=(entry.probability*100).toFixed(2)+'%';label.append(letter,text,percent);const track=document.createElement('div');track.className='bar-track';const fill=document.createElement('div');fill.className='bar-fill';fill.style.width=(entry.probability*100)+'%';track.append(fill);row.append(label,track);$('probabilities').append(row);});$('request-time').textContent=`${t('request')} ${(output.elapsed_ms/1000).toFixed(2)}s`;$('token-count').textContent=`${output.tokens} ${t('tokens')}`;$('raw-json').textContent=JSON.stringify(output,null,2);$('result').hidden=false;$('response-section').hidden=false;$('empty-result').hidden=true;}
function setLanguage(value){lang=value;$('error').hidden=true;document.documentElement.lang=lang;document.title=lang==='ko'?'Kev Playground — 선택을 위한 모델':'Kev Playground — A model for decisions';document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n);});$('lang-ko').setAttribute('aria-pressed',String(lang==='ko'));$('lang-en').setAttribute('aria-pressed',String(lang==='en'));renderExamples();renumber();showHealth();renderResult();}
$('lang-ko').onclick=()=>setLanguage('ko');$('lang-en').onclick=()=>setLanguage('en');
$('add-option').onclick=()=>{if(optionValues().length<12){addOption().focus();clearResult();}};
$('decision-form').addEventListener('input',()=>{clearResult();currentExample='';renderExamples();});
$('copy-json').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(output,null,2));$('copy-json').textContent=t('copied');}catch{$('copy-json').textContent=t('copyFail');}setTimeout(()=>{$('copy-json').textContent=t('copy');},2500);};
$('decision-form').onsubmit=async(event)=>{event.preventDefault();if(busy)return;const body={state:$('state').value.trim(),question:$('question').value.trim(),options:optionValues().map(s=>s.trim())};clearResult();if(!body.state||!body.question||body.options.some(s=>!s)||new Set(body.options).size!==body.options.length){$('error').textContent=t('invalid');$('error').hidden=false;return;}busy=true;$('fields').disabled=true;$('decision-form').setAttribute('aria-busy','true');renderExamples();showHealth();try{const response=await fetch('/api/decide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(180000)});const data=await response.json();if(!response.ok){let msg=response.status===429?t('busy'):t('genericError');if(response.status===422)msg=typeof data.detail==='string'&&/long|overflow|token/i.test(data.detail)?t('longInput'):t('invalid');throw Error(msg);}output=data;renderResult();}catch(error){$('error').textContent=error.name==='TimeoutError'?t('genericError'):error.message;$('error').hidden=false;}finally{busy=false;$('fields').disabled=false;$('decision-form').setAttribute('aria-busy','false');renumber();renderExamples();showHealth();}};
async function init(){setLanguage('ko');try{const response=await fetch('/api/examples');if(!response.ok)throw Error();examples=await response.json();loadExample(examples[0]);}catch{$('error').textContent=t('genericError');$('error').hidden=false;addOption();addOption();}await refreshHealth();setInterval(refreshHealth,6000);}
init();
